solution for 392
Leetcode-Tutorial/Tutorial pull request #1
Opened 2017-02-19 03:15 UTC by lamxTyler

PTAL @livc  @AaronTengDeChuan  @yizhen20133868

2017-02-19 03:38 UTC, lamxTyler commented
PTAL(please take a look)
如果觉得没问题，comment一个LGTM(looks good to me).
凑足两个LGTM就可以合进去了

2017-02-19 08:11 UTC, yizhen20133868 commented
LGTM

2017-02-19 08:12 UTC, Kelukin commented
LGTM

2017-02-19 08:17 UTC, AaronTengDeChuan requested changes

2017-02-19 08:17 UTC, AaronTengDeChuan commented on 392-IsSubsequence/solution.md
> +j还是小于6，`t[5]=c`,`s[2]=c`,此时它们相等，`i++`，`i=3`，此时等于`s_len`，`res=true`，跳出while循环，返回结果为`true`.
说完解题思路、举一个例子走一遍算法之后，应该简单说一下这种贪心算法的正确性吧？？？

2017-02-19 08:21 UTC, lamxTyler commented on 392-IsSubsequence/solution.md
> +j还是小于6，`t[5]=c`,`s[2]=c`,此时它们相等，`i++`，`i=3`，此时等于`s_len`，`res=true`，跳出while循环，返回结果为`true`.
@yizhen20133868 正确性是要解释下

2017-02-19 08:58 UTC, lamxTyler commented
把`solution.md`重命名为`README.md`后在点进文件夹后可以直接看到题解内容，而不用再点进`.md`看

2017-02-19 10:59 UTC, livc commented
1. 题解和代码都放一个文件里吧？内容并不多，读的时候还得来回切换。
2. 自己选题如何？为何防止重复，可以在开始做的时候发起一个 PR 或 issue

2017-02-19 11:28 UTC, lamxTyler commented
1.其实这么做，当初想的是，看题解的时候尽量不要看到代码，而是理解后尝试自己实现，所以才分开。
2.同意，提issue吧。
@livc

2017-02-19 12:11 UTC, yizhen20133868 commented
我个人倾向于放俩个文件，不那么容易看见代码~不是重点~

其实是最好一个人分配，10个人自由选有点过于杂乱了，无法充分利用多人的优势，可以这样，分专题给某几个人，然后那几个人对这个专题的题目进行自由选择，这样的话，进度和效率随着时间也会提高。 你们觉得呢？@livc @lamxTyler @Kelukin @su526664687 @AaronTengDeChuan

2017-02-19 12:35 UTC, qinlibo-hit approved these changes

2017-02-19 12:35 UTC, qinlibo-hit commented on 392-IsSubsequence/solution.md
> +j还是小于6，`t[5]=c`,`s[2]=c`,此时它们相等，`i++`，`i=3`，此时等于`s_len`，`res=true`，跳出while循环，返回结果为`true`.
收到，可以~ @AaronTengDeChuan @lamxTyler

2017-02-19 12:35 UTC, qinlibo-hit commented on 392-IsSubsequence/solution.md
> +j还是小于6，`t[5]=c`,`s[2]=c`,此时它们相等，`i++`，`i=3`，此时等于`s_len`，`res=true`，跳出while循环，返回结果为`true`.
晚上写一下~

2017-02-19 12:40 UTC, su526664687 commented
@yizhen20133868  分配题目ok

2017-02-19 12:44 UTC, yizhen20133868 commented
那好的，我会尽量保证满足每个小伙伴，尽量根据大家的喜好去分配，我会重新申请一个账号，这样的话，分配题目也就不会乱了，大家都用那个账号即可，没有ac的题目，会有显示.大家去LeetCode网站看一下，标签栏目，把最愿意写的5个专题名字告知一下~不知这样大家是否同意~ @Kelukin @livc @su526664687 @AaronTengDeChuan @lamxTyler

2017-02-19 13:17 UTC, Kelukin commented
@yizhen20133868  挺赞成分专题的，效率会高很多

2017-02-19 13:29 UTC, yizhen20133868 commented
好的，现在俩个方法，一个是所有题目自己挑选，一个是分专题分人来写，第二种方法好处是，同时可以覆盖所有专题，并进，效率较高，还有就是同专题风格容易统一，觉得想要方法1好的回复1，想要方法2的回复2，哪个票数多，就用哪个方法~ @lamxTyler @Kelukin @livc @su526664687 @AaronTengDeChuan

2017-02-19 14:03 UTC, lamxTyler commented
首先两种方法的共同前提是：使用同一个leetcode账号，这样子大家容易知道哪些题目还没人搞；还有就是在某个范围内题目自由选择。
第二种的好处 @yizhen20133868 已经说了，我来补充几点：
* 分专题分人的话，各个专题题目数量分布不均衡，难度不均衡；
* 风格统一是好处，也有不好的地方，就是不同的人有不同的品味，可能有的受众喜欢风格a，有的喜欢风格b。不同的人写的话，可以多种风格都有。

2017-02-19 14:38 UTC, lamxTyler commented
@yizhen20133868 已经提交了

















































































































































































































@AaronTengDeChuan  已经添加证明了，PTAL

2017-02-19 14:50 UTC, AaronTengDeChuan approved these changes
LGTM

2017-02-19 14:51 UTC, merged

2017-02-20 00:07 UTC, 601442991 commented
2