add 448 485
Leetcode-Tutorial/Tutorial pull request #10
Opened 2017-02-25 14:22 UTC by livc

solve #6

2017-02-25 15:01 UTC, alivxxx requested changes

2017-02-25 15:01 UTC, lamxTyler commented on 448. Find All Numbers Disappeared in an Array/README.md
> +由于规定了空间复杂度，我们只能使用给定的数组 nums，因此先遍历一次，将每个数字作为数组位置的那个数字置为负数，再遍历第二次，正数的位置就是没有出现的数字。
* 规定空间复杂度并不是只能用给定数组的原因，O(k*n)=>O(n)。
* 这个`因此`感觉很突兀，前面说的并不是后面的原因。
* 可以像392那样，先写一个用额外空间的算法，比方说一个vis数组，那么你这里打标记的方式就有迹可循了，因为你这里本质也在打标记，不然的话，这个算法就像魔法一样蹦出来一样。
* 最好可以像392一样有一个简单的例子，可以不用这么多语言描述，就大概的列一下数组的变化就好，因为说实话，上面那段话，一开始我没读懂= =

2017-02-25 15:01 UTC, lamxTyler commented on 485. Max Consecutive Ones/README.md
> +0 和 1 组成的数组，找出其中连续出现次数最多的 1.
这么说不恰当吧，不是次数，是长度

2017-02-25 15:01 UTC, lamxTyler commented on 485. Max Consecutive Ones/README.md
> +遍历数组，用一个变量每次加上当前位置的值，如果值没有改变说明此位置为 0，这时更新 ans.
* 可以解释一下这个变量是什么含义，它起什么作用

2017-02-25 15:07 UTC, lamxTyler commented on 448. Find All Numbers Disappeared in an Array/solution.cpp
> +
为啥有个空行= =

2017-02-25 15:26 UTC, livc commented on 448. Find All Numbers Disappeared in an Array/README.md
> +由于规定了空间复杂度，我们只能使用给定的数组 nums，因此先遍历一次，将每个数字作为数组位置的那个数字置为负数，再遍历第二次，正数的位置就是没有出现的数字。
> 先写一个用额外空间的算法

这个感觉没必要吧，如果有更好的解法就可以补充，没有更优的就不要写了，又不是很难理解。

2017-02-26 07:40 UTC, alivxxx submitted a review, later dismissed

2017-02-27 12:16 UTC, qinlibo-hit commented on 448. Find All Numbers Disappeared in an Array/README.md
> +由于规定了空间复杂度，我们只能使用给定的数组 nums，因此先遍历一次，将每个数字作为数组位置的那个数字置为负数，再遍历第二次，正数的位置就是没有出现的数字。
小钊，我觉得有必要，392也不难也是解法一，解法二递进过来，这个项目主要目标是给别人看的，所以需要我们把别人当小白来看，才能体现我们的通俗易懂严谨风格（这才有10个人维护），所以再加一个解法，用语言说明一下，额外开一个空间，记录，然后容易理解，再过渡到第二个算法，因为不允许新开空间，所以再原地修改，这样可能对他人更好理解。 @livc @lamxTyler

2017-02-27 12:16 UTC, qinlibo-hit commented on 448. Find All Numbers Disappeared in an Array/solution.cpp
> +
这里我觉得需要在源代码注释一下，为什么必须要tmp大于0的时候，再修改的原因，因为原文数组可能会出现重复数字.

2017-02-27 12:33 UTC, AaronTengDeChuan requested changes

2017-02-27 12:33 UTC, AaronTengDeChuan commented on 448. Find All Numbers Disappeared in an Array/solution.cpp
> +            if(tmp > 0){
这个代码AC不了，有运行错误。
第7行，判断条件 tmp>0， 改为 tmp>=0;
第13行，表达式 tmp=-tmp，改为 tmp=-tmp-2.

2017-03-04 07:33 UTC, yizhen20133868 commented on 448. Find All Numbers Disappeared in an Array/README.md
> +由于规定了空间复杂度，我们只能使用给定的数组 nums，因此先遍历一次，将每个数字作为数组位置的那个数字置为负数，再遍历第二次，正数的位置就是没有出现的数字。
小钊补写一个用额外空间的算法吧，作为解法一 @livc

2017-03-05 02:57 UTC, lamxTyler commented
@AaronTengDeChuan  PTAL

2017-03-05 04:10 UTC, AaronTengDeChuan approved these changes
LGTM

2017-03-05 04:20 UTC, merged