Add solutions for 513 and 515.
Leetcode-Tutorial/Tutorial pull request #18
Opened 2017-03-03 08:18 UTC by yizhen20133868

2017-03-04 07:34 UTC, AaronTengDeChuan requested changes

2017-03-04 07:34 UTC, AaronTengDeChuan commented on 513-Find Bottom Left Tree Value/solution for 513.md
> +树的题目我们很容易想到递归，或者遍历来求，因为基于树的一些问法，我们都可以变换到遍历树然后到达那个结点再操作。那么我首先想的是用先序遍历来做，我们维护一个最大深度和该深度的结点值，由于先序遍历遍历的顺序是左-根-右，所以每一行最左边的结点肯定最先遍历到，那么由于是新一行，那么当前深度肯定比之前的最大深度大，所以我们可以更新最大深度为当前深度，结点值result为当前结点值（深度比当前记录的深度大
先序遍历的顺序是根-左-右，中序遍历才是左-根-右，中序遍历时每一行最左边的结点肯定最先遍历到，你看看你想用哪个。。。另外递归的代码也贴上来吧。 @yizhen20133868

2017-03-04 07:36 UTC, yizhen20133868 commented on 513-Find Bottom Left Tree Value/solution for 513.md
> +树的题目我们很容易想到递归，或者遍历来求，因为基于树的一些问法，我们都可以变换到遍历树然后到达那个结点再操作。那么我首先想的是用先序遍历来做，我们维护一个最大深度和该深度的结点值，由于先序遍历遍历的顺序是左-根-右，所以每一行最左边的结点肯定最先遍历到，那么由于是新一行，那么当前深度肯定比之前的最大深度大，所以我们可以更新最大深度为当前深度，结点值result为当前结点值（深度比当前记录的深度大
ok @AaronTengDeChuan

2017-03-05 02:58 UTC, lamxTyler commented
@AaronTengDeChuan  PTAL

2017-03-05 04:11 UTC, AaronTengDeChuan approved these changes
LGTM

2017-03-05 04:21 UTC, merged