solution for 312,403
Leetcode-Tutorial/Tutorial pull request #20
Opened 2017-03-03 10:32 UTC by lamxTyler

2017-03-04 00:29 UTC, yizhen20133868 commented on 312-Burst Balloons/README.md
> +在实现的时候，我们可以手动在两端加上价值为1的气球，这样子f(i,j)可以重定义为从i炸到j，最后剩下两端的i,j时的最优值。这样子实现起来没有corner case。
滨滨，能不能像下面那个题解一样，举个很简单的例子放 @lamxTyler

2017-03-04 07:01 UTC, AaronTengDeChuan requested changes

2017-03-04 07:01 UTC, AaronTengDeChuan commented on 312-Burst Balloons/README.md
> +为什么`[1,5...]`和`[5,1...]`是一样的呢？因为在这个时候1和5气球之间有[2,3,4]的障碍，也就是说除非[2,3,4]都炸完了，那么[1,5]之间的顺序才是有关系的；也就是说在有障碍阻隔的情况下，两端是不可能相互影响的，它们之间谁先炸都无所谓。
[1,5,2,3,4]和[5,1,2,3,4] 这个例子和之后的解法没有太大的联系，说实话这个例子我没看懂。。。 @ @lamxTyler

2017-03-04 07:01 UTC, AaronTengDeChuan commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
这里的 i 和 j 代表的位置应该是边界位置，滨滨应该说清楚啊，要不然容易混淆。
还有最后一段对处理边界条件的说明就在这一起说了吧，别分开说，容易给读者造成你这里没有手动加上价值为1的气球的错觉。

2017-03-05 03:01 UTC, lamxTyler commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
边界位置和区间有什么区别么？
这里本来就没有加1，这里是需要特判的，只是加了1之后不用特判而已。

2017-03-05 03:01 UTC, lamxTyler commented on 312-Burst Balloons/README.md
> +为什么`[1,5...]`和`[5,1...]`是一样的呢？因为在这个时候1和5气球之间有[2,3,4]的障碍，也就是说除非[2,3,4]都炸完了，那么[1,5]之间的顺序才是有关系的；也就是说在有障碍阻隔的情况下，两端是不可能相互影响的，它们之间谁先炸都无所谓。
这个东西是爆炸顺序。

2017-03-05 03:35 UTC, AaronTengDeChuan commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
在计算 f(i,k-1) 的时候，是要枚举 i 到 k-1区间内的最后一个爆炸的气球，应该考虑 i 的左边气球， k-1 的右边气球吧。

2017-03-05 03:49 UTC, lamxTyler commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
不用考虑。f(i,j)的意义就是只考虑这一段，其他部分的不受影响。

2017-03-05 04:08 UTC, AaronTengDeChuan commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
计算 f(i,j) 的时候，枚举 k 为最后一个炸掉的气球，这时要计算 f(i,k-1) 和 f(k+1,j)，在计算 f(i,k-1） 还是要枚举最后一个爆炸的气球，如果 i 到 k-1 中选择最后一个爆炸的气球是 k-1 ，爆炸 k-1 号气球得到的值是不是 nums[k-2]*nums[k-1]*nums[k]（因为 k 比 k-1 晚爆炸）。这样来看计算 f(i,k-1）时就不是只考虑这一段了，这一段不影响其他部分，但是受其他部分影响。
所以我觉得，其实在这里就已经模拟了两端的气球，只不过不炸它们罢了。 
整体写的特别好，就是这里的细节优点模糊。@lamxTyler

2017-03-05 04:18 UTC, lamxTyler commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
其他部分不受影响，同时也不受其他部分影响。最后一个是K-1,得到的是num[i-1]*num[k-1]*num[k]

2017-03-05 04:23 UTC, AaronTengDeChuan commented on 312-Burst Balloons/README.md
> +更规范的说，令f(i,j)为i到j区间爆炸的最优值，我们去枚举最后一个炸掉的气球k，那么就可以得到`f(i,j)=max(f(i,k-1)+f(k+1,j)+nums[k]*nums[i]*nums[j])`。
嗯，我看了你的例子了，已经清楚了。 @lamxTyler

2017-03-05 04:25 UTC, AaronTengDeChuan approved these changes
LGTM

2017-03-05 04:39 UTC, lamxTyler commented
@yizhen20133868  PTAL

2017-03-05 09:45 UTC, merged