solution for 336, 480
Leetcode-Tutorial/Tutorial pull request #60
Opened 2017-03-17 07:31 UTC by 601442991

2017-03-17 07:39 UTC, 601442991 commented
没什么冲突应该会自动合并吧。。。。。是不是只有merge总仓库后再add才不会把之前的commit加进来？and，看daolao们的仓库怎么都保持在初始状态没什么更新啊【菜不成声】

2017-03-17 11:34 UTC, lamxTyler commented
要merge这个仓库的master，而不是你fork过去的。不建议fork过去，直接在这个仓库里搞就好了。

2017-03-17 14:24 UTC, lamxTyler commented on 480-SlidingWindowMedian/README.md
> +����˼·2��������ֻ��һ��`multiset`��һ������ָ�롣�����ָ��ָ����λ�������ɾ��ʱ���ʵ���������ָ���ָ�򼴿ɡ�
这个没问题么？每次对一个STL的容器修改，都可能引起迭代器失效

2017-03-18 02:26 UTC, AaronTengDeChuan requested changes

2017-03-18 02:26 UTC, AaronTengDeChuan commented on 336-PalindromePairs/README.md
> +�������ַ��������`map`������ÿ���ַ�`s`��ö�ٷָ��`pos`������`[pos ~ s.size()-1]`�ǻ��Ĵ�����`[0 ~ pos-1]`���洮��`map`�д��ڡ�ʱ�临�Ӷ�Ϊ`O(n*K)`��
思路2的代码在哪里呀。 @601442991

2017-03-18 03:29 UTC, 601442991 commented on 480-SlidingWindowMedian/README.md
> +����˼·2��������ֻ��һ��`multiset`��һ������ָ�롣�����ָ��ָ����λ�������ɾ��ʱ���ʵ���������ָ���ָ�򼴿ɡ�
没问题，不erase迭代器自己就不会失效。

2017-03-19 07:47 UTC, AaronTengDeChuan approved these changes

2017-03-19 08:22 UTC, merged